name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.10.0
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: 1
          BLACKDUCK_TRUST_CERT: true
          DETECT_ACCURACY_REQUIRED: none
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          
        with:
          ### SCANNING: Required fields
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
         
          ### SCANNING: Optional fields
          # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackduck_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
          blackduck_fixpr_enabled: true
          blackduck_fixpr_maxCount: 5
          blackduck_fixpr_filter_severities: 'CRITICAL,HIGH,MEDIUM'
          blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackduck_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          # blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true
